### ISSUE TITLE
cmake: XMLRPC not found

### ISSUE THREAD

**Issue by fabroggy** [ros/catkin#1163]
We are using ros:noetic
Recently (1 week ago from now), it seems that cmake was not able to find xmlrpc package

We first run rosdep install --from-paths src --ignore-src -y.
We can see that xmlrpc is installed in the logs:

"The following additional packages will be installed:
  libxmlrpc-c++8v5 libxmlrpc-core-c3 libxmlrpc-core-c3-dev
Suggested packages:
  xmlrpc-api-utils
The following NEW packages will be installed:
  libxmlrpc-c++8-dev libxmlrpc-c++8v5 libxmlrpc-core-c3 libxmlrpc-core-c3-dev
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
The following additional packages will be installed:
  libxmlrpc-c++8v5 libxmlrpc-core-c3 libxmlrpc-core-c3-dev
Suggested packages:
  xmlrpc-api-utils
The following NEW packages will be installed:
  libxmlrpc-c++8-dev libxmlrpc-c++8v5 libxmlrpc-core-c3 libxmlrpc-core-c3-dev
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded."

We then run catkin_make and then cmake reports that it cannot find XMLRPC that:
"CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  XMLRPC was not found.  Make sure the entries XMLRPC_* are set.  (missing:
  XMLRPC_C_FOUND)

Checking At CMakeErrors.log, it seems that it cannot find libpthread:
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /root/ws/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_0de78/fast && /usr/bin/make -f CMakeFiles/cmTC_0de78.dir/build.make CMakeFiles/cmTC_0de78.dir/build
make[1]: Entering directory '/root/ws/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0de78.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_0de78.dir/src.c.o   -c /root/ws/build/CMakeFiles/CMakeTmp/src.c     
Linking C executable cmTC_0de78
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0de78.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    -rdynamic CMakeFiles/cmTC_0de78.dir/src.c.o  -o cmTC_0de78
/usr/bin/ld: CMakeFiles/cmTC_0de78.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_0de78.dir/build.make:87: cmTC_0de78] Error 1
make[1]: Leaving directory '/root/ws/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_0de78/fast] Error 2

Do you happen to have a clue about what is happening please?

**Comment by gbiggs** [comment]
I think this is a problem with your system. Can you try in a clean environment?

Do you have a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by fabroggy** [comment]
I pulled the latest ros:noetic docker image and ran it.
I created a small CMakeLists.txt and added : 
find_package (XMLRPC REQUIRED c++2 client)


THe output is the following:
 No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  XMLRPC was not found.  Make sure the entries XMLRPC_* are set.  (missing:
  XMLRPC_C_FOUND XMLRPC_LIBRARIES)
Call Stack (most recent call first):
  usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  usr/share/cmake-3.16/Modules/FindXMLRPC.cmake:126 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  //CMakeLists.txt:1 (find_package)


CMake Warning (dev) in //CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.16)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "//CMakeFiles/CMakeOutput.log".

I had a look at the CMakeOutputs.log and there is no error inside...

I tried different cmake version, but it does not work
Can you reproduce the error on your side ?

cmake version 3.16.3.

**Comment by fabroggy** [comment]
Additonally, i also installed XMLRPC-C separatly:
apt-get install libxmlrpc-core-c3-dev

But i still have the same error

**Comment by fabroggy** [comment]
I also checked which xmlrpc packages i have:
 apt list --installed | grep -i xmlrpc

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libxmlrpc-c++8-dev/focal,now 1.33.14-8build2 amd64 [installed]
libxmlrpc-c++8v5/focal,now 1.33.14-8build2 amd64 [installed,automatic]
libxmlrpc-core-c3-dev/focal,now 1.33.14-8build2 amd64 [installed]
libxmlrpc-core-c3/focal,now 1.33.14-8build2 amd64 [installed,automatic]
ros-noetic-xmlrpcpp/focal,now 1.15.14-1focal.20220106.232911 amd64 [installed,automatic]

**Comment by fabroggy** [comment]
So i updated : find_package (XMLRPC REQUIRED c++2 client) to find_package (XMLRPC REQUIRED) on my docker image and relaunch catkin_make
It has found XMLRPC packages. But later on, it crashed when  linking. It gave the following log:

/usr/bin/ld: CMakeFiles/psud.dir/src/psu_driver.cpp.o: in function `xmlrpc_c::value_string::~value_string()':
psu_driver.cpp:(.text._ZN8xmlrpc_c12value_stringD2Ev[_ZN8xmlrpc_c12value_stringD5Ev]+0x18): undefined reference to `xmlrpc_c::value::~value()'
/usr/bin/ld: CMakeFiles/psud.dir/src/psu_driver.cpp.o: in function `xmlrpc_c::value_int::~value_int()':
psu_driver.cpp:(.text._ZN8xmlrpc_c9value_intD2Ev[_ZN8xmlrpc_c9value_intD5Ev]+0x18): undefined reference to `xmlrpc_c::value::~value()'
/usr/bin/ld: CMakeFiles/psud.dir/src/psu_driver.cpp.o: in function `xmlrpc_c::rpcOutcome::~rpcOutcome()':
psu_driver.cpp:(.text._ZN8xmlrpc_c10rpcOutcomeD2Ev[_ZN8xmlrpc_c10rpcOutcomeD5Ev]+0x2c): undefined reference to `xmlrpc_c::value::~value()'
/usr/bin/ld: CMakeFiles/psud.dir/src/psu_driver.cpp.o: in function `xmlrpc_c::rpcOutcome::rpcOutcome(xmlrpc_c::rpcOutcome&&)':
psu_driver.cpp:(.text._ZN8xmlrpc_c10rpcOutcomeC2EOS0_[_ZN8xmlrpc_c10rpcOutcomeC5EOS0_]+0x47): undefined reference to `xmlrpc_c::value::value(xmlrpc_c::value const&)'
/usr/bin/ld: CMakeFiles/psud.dir/src/psu_driver.cpp.o: in function `rosasio::Connection::on_read(boost::system::error_code)':
psu_driver.cpp:(.text._ZN7rosasio10Connection7on_readEN5boost6system10error_codeE[_ZN7rosasio10Connection7on_readEN5boost6system10error_codeE]+0x109): undefined reference to `xmlrpc_c::paramList::paramList(unsigned int)'
/usr/bin/ld: psu_driver.cpp:(.text._ZN7rosasio10Connection7on_readEN5boost6system10error_codeE[_ZN7rosasio10Connection7on_readEN5boost6system10error_codeE]+0x129): undefined reference to `xmlrpc_c::xml::parseCall(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, xmlrpc_c::paramList*)'
/usr/bin/ld: psu_driver.cpp:(.text._ZN7rosasio10Connection7on_readEN5boost6system10error_codeE[_ZN7rosasio10Connection7on_readEN5boost6system10error_codeE]+0x1e2): undefined reference to `xmlrpc_c::xml::generateResponse(xmlrpc_c::rpcOutcome const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
/usr/bin/ld: CMakeFiles/psud.dir/src/psu_driver.cpp.o: in function `auto rosasio::Node::Node(boost::asio::io_context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(auto:1&)#1}::operator()<xmlrpc_c::paramList const>(xmlrpc_c::paramList const&)

I think methods have not been compiled with c++ flag, therefore it cannot find them. Would it mean consequently xmlrpc c++ are not installed on ros:noetic docker image ?
THe weird thing is that  (XMLRPC REQUIRED c++2 client) works fine on a classic Linux Ubuntu  20.04 desktop

**Comment by fabroggy** [comment]
Found the issue: libcurl4-gnutls-dev is missing from ros image
apt install libcurl4-gnutls-dev solves the issue
