### ISSUE TITLE
rosdep installing the dependencies fails on OSX 10.10

### ISSUE THREAD

**Issue by chintak** [ros/catkin#697]
Hi,

I am trying to setup ros on OSX 10.10. I'm following the installation instructions given [here](http://wiki.ros.org/indigo/Installation/OSX/Homebrew/Source#indigo.2BAC8-Installation.2BAC8-Source.Building_the_catkin_Packages). While resolving the dependencies using this command:

`rosdep install --from-paths src --ignore-src --rosdistro indigo -y`

I get an `ld: symbol(s) not found for architecture x86_64` error while installing `collada-dom` and `opencv`. This I guess is associated with the default stdlib for clang being `libc++` instead of `libstdc++`. 

So I tried to install the dependencies of `collada-dom` with `libstdc++`. I was able to install Boost successfully but am unable to figure out how to install pcre with `libstdc++`. 

Also for opencv I installed it using `libstdc++` using the formula provided [here](https://github.com/NikolausDemmel/homebrew-devel/blob/master/opencv-libstdcxx.rb), but this is just a keg-only formula. Even though I symlinked myself, rosdep isn't detecting this version.

Any help is much appreciated. Has anyone been able to get it working on OSX 10.10?

**Comment by wjwwood** [comment]
Hi @chintak,

This really isn't the correct repository for this kind of issue, since it really doesn't have anything to do with catkin. Please ask this question on answers.ros.org.

Others have gotten Indigo working on 10.10 without many problems, I haven't heard of this specific issue myself.

I'm going to close this, but please open a question on answers.ros.org and make sure you tag it with os x and rosdep, then link it here in a comment and I will take a look when I have time.

**Comment by chintak** [comment]
@wjwwood, I've posted the question here: http://answers.ros.org/question/198391/rosdep-installing-the-dependencies-fails-on-osx-1010/
